services:
  tempo:
    image: grafana/tempo:2.6.0
    container_name: tempo
    restart: unless-stopped
    ports:
      - "3200:3200"   # HTTP query/API
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    volumes:
      - tempo_data:/var/tempo
    configs:
      - source: tempo_config
        target: /etc/tempo.yaml
    command: -config.file=/etc/tempo.yaml
    networks:
      - network_swarm_public

configs:
  tempo_config:
    file: ./tempo_config.yml

volumes:
  tempo_data:

networks:
  network_swarm_public:
    external: true
